# Generated by Django 5.2.5 on 2025-09-13 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0110_user_robots_txt'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reading_time_on',
            field=models.BooleanField(default=False, help_text='Add an estimated reading time - in minutes - to the top of the post body.', verbose_name='Show Reading Time on Posts'),
        ),
        migrations.AlterField(
            model_name='user',
            name='robots_txt',
            field=models.TextField(blank=True, default='User-agent: *\nDisallow:\nAllow: /', help_text='Custom robots.txt content for your blog. Leave blank for default.', null=True, verbose_name='robots.txt'),
        ),
    ]
