# Generated by Django 5.2.5 on 2025-09-13 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0111_user_reading_time_on_alter_user_robots_txt'),
    ]

    operations = [
        migrations.CreateModel(
            name='rsl_settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license', models.CharField(max_length=1024)),
                ('show_http', models.BooleanField(default=True)),
                ('show_rss', models.BooleanField(default=False)),
                ('show_robotstxt', models.BooleanField(default=True)),
                ('show_webpage', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
