# Generated by Django 5.2.5 on 2025-09-13 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0112_rsl_settings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='rsl_settings',
            new_name='ReallySimpleLicensing',
        ),
    ]
