# Generated by Django 5.2.5 on 2025-09-13 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0113_rename_rsl_settings_reallysimplelicensing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reallysimplelicensing',
            name='show_rss',
            field=models.BooleanField(default=True),
        ),
    ]
