# Generated by Django 5.2.5 on 2025-09-13 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0114_alter_reallysimplelicensing_show_rss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reallysimplelicensing',
            name='license',
            field=models.TextField(blank=True, null=True),
        ),
    ]
