# Generated by Django 5.2.5 on 2025-09-13 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0115_alter_reallysimplelicensing_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reallysimplelicensing',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reallysimplelicensing', to=settings.AUTH_USER_MODEL),
        ),
    ]
