# Generated by Django 5.2.5 on 2025-09-13 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0116_alter_reallysimplelicensing_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reallysimplelicensing',
            name='license',
            field=models.TextField(blank=True, help_text='License text in XML format defined by the Really Simple Licensing standard. Will be available at /license.xml.', null=True),
        ),
        migrations.AlterField(
            model_name='reallysimplelicensing',
            name='show_http',
            field=models.BooleanField(default=True, help_text='Show/hide license in HTTP header.', verbose_name='Show HTTP License'),
        ),
        migrations.AlterField(
            model_name='reallysimplelicensing',
            name='show_robotstxt',
            field=models.BooleanField(default=True, help_text='Show/hide license in robots.txt.', verbose_name='Show robots.txt License'),
        ),
        migrations.AlterField(
            model_name='reallysimplelicensing',
            name='show_rss',
            field=models.BooleanField(default=True, help_text='Show/hide license in RSS feed.', verbose_name='Show RSS License'),
        ),
        migrations.AlterField(
            model_name='reallysimplelicensing',
            name='show_webpage',
            field=models.BooleanField(default=True, help_text='Show/hide license on webpage header.', verbose_name='Show Webpage License'),
        ),
    ]
