# Generated by Django 5.2.5 on 2025-09-17 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0117_alter_reallysimplelicensing_license_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='markdown_link_paste_on',
            field=models.BooleanField(default=False, help_text='Enable/disable automatic markdown link formatting on paste.', verbose_name='Auto Markdown link formatting'),
        ),
        migrations.AlterField(
            model_name='user',
            name='subscribe_note',
            field=models.CharField(blank=True, default='Subscribe via [RSS](/rss/) / [Atom](/atom/) / [via Email](/newsletter/).', help_text='Default: Subscribe via [RSS](/rss/) / [Atom](/atom/) / [via Email](/newsletter/).', max_length=350, null=True),
        ),
    ]
