# Generated by Django 5.2.5 on 2025-09-17 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0118_user_markdown_link_paste_on_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='markdown_link_paste_on',
        ),
        migrations.AddField(
            model_name='user',
            name='markdown_auto_format_on',
            field=models.BooleanField(default=False, help_text='Enable/disable automatic markdown formatting.', verbose_name='Auto Markdown formatting'),
        ),
    ]
