# Generated by Django 5.2.5 on 2025-09-20 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0119_remove_user_markdown_link_paste_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='number_of_posts_feed',
            field=models.IntegerField(default=10, help_text='Number of posts to show in RSS/Atom feed. Default is 10.', verbose_name='Number of Posts in Feed'),
        ),
    ]
