# Generated by Django 5.2.5 on 2025-09-20 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0120_user_number_of_posts_feed'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
    ]
