# Generated by Django 5.2.5 on 2025-09-24 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0121_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='show_tags_in_post_list',
            field=models.BooleanField(default=True, help_text='Show/hide tags in the post list.', verbose_name='Show Tags In Post List'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.CharField(blank=True, default=None, help_text='Enter comma-separated tags (e.g., django, python, blog).', max_length=300, null=True),
        ),
    ]
