# Generated by Django 5.2.5 on 2025-09-25 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0122_user_show_tags_in_post_list_alter_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='custom_css',
            field=models.TextField(blank=True, default='', help_text='Custom CSS for your blog to override certain parts, or all of, the default theme. Leave blank for no overrides.', null=True, verbose_name='Custom CSS'),
        ),
    ]
