# Generated by Django 5.2.5 on 2025-09-25 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0123_user_custom_css'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='custom_css',
            field=models.TextField(blank=True, default='', help_text="Custom CSS for your blog to override certain parts, or all of, the default theme. Leave blank for no overrides. Click <a href='https://docs.bocpress.co.uk/custom-css/' target='_blank' rel='noopener noreferrer'>here</a> to learn about the allowed CSS properties.", null=True, verbose_name='Custom CSS'),
        ),
    ]
